# Generated by Django 4.2.4 on 2023-12-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('telefono', models.IntegerField()),
                ('fecha_reserva', models.DateField()),
                ('hora', models.TimeField()),
                ('cantidad_personas', models.IntegerField()),
                ('correo', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=15)),
            ],
        ),
    ]
